from __future__ import annotations

import numpy as np
from keybert import KeyBERT
from sentence_transformers import SentenceTransformer
from sklearn.cluster import AgglomerativeClustering

_embed_model: SentenceTransformer | None = None
_kw_model: KeyBERT | None = None


def load_embed_model() -> SentenceTransformer:
    """Load (or return cached) sentence-transformer model."""
    global _embed_model, _kw_model
    if _embed_model is None:
        # ~80 MB download on first run; cached in ~/.cache/huggingface afterwards
        _embed_model = SentenceTransformer("all-MiniLM-L6-v2")
        _kw_model = KeyBERT(model=_embed_model)
    return _embed_model


def build_sections(paragraphs: list[dict]) -> list[dict]:
    """
    Cluster paragraphs by semantic similarity and return sections with
    keyphrase headers generated by KeyBERT.

    Each returned section has the shape:
        { "header": str, "paragraphs": list[dict] }
    where the paragraphs are the (cleaned) originals in their original order.
    """
    n = len(paragraphs)

    if n == 0:
        return []

    if n == 1:
        return [{"header": _make_header(paragraphs[0]["text"]),
                 "paragraphs": paragraphs}]

    texts = [p["text"] for p in paragraphs]

    # Encode paragraphs → L2-normalised embeddings (Ward on L2-normed ≈ cosine)
    model = load_embed_model()
    embeddings = model.encode(texts, show_progress_bar=False, normalize_embeddings=True)

    # Target cluster count: roughly 1 section per 3 paragraphs, clamped 2–8
    n_clusters = max(2, min(8, round(n / 3)))
    n_clusters = min(n_clusters, n)  # can't exceed number of samples

    clustering = AgglomerativeClustering(
        n_clusters=n_clusters,
        metric="euclidean",
        linkage="ward",
    )
    labels: np.ndarray = clustering.fit_predict(embeddings)

    # Walk paragraphs in order; start a new section whenever the cluster label changes.
    # This preserves temporal/narrative order in the transcript.
    raw_sections: list[list[int]] = []
    current_group: list[int] = [0]

    for i in range(1, n):
        if labels[i] == labels[i - 1]:
            current_group.append(i)
        else:
            raw_sections.append(current_group)
            current_group = [i]
    raw_sections.append(current_group)

    sections: list[dict] = []
    for indices in raw_sections:
        section_text = " ".join(texts[i] for i in indices)
        header = _make_header(section_text)
        sections.append({
            "header": header,
            "paragraphs": [paragraphs[i] for i in indices],
        })

    return sections


def _make_header(section_text: str) -> str:
    """Use KeyBERT to extract the most representative keyphrase as the header."""
    global _kw_model
    if _kw_model is None or not section_text.strip():
        return "General"

    try:
        keywords = _kw_model.extract_keywords(
            section_text,
            keyphrase_ngram_range=(1, 3),
            stop_words="english",
            top_n=1,
        )
        if keywords:
            # keywords is a list of (keyphrase, score) tuples
            return keywords[0][0].title()
        return "General"
    except Exception:
        return "General"
